name: Build and Test

on:
  push:
    branches:
      - lab2
  pull_request:
    branches:
      - master
      - lab2

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev

      # Step 3: Build Google Test
      - name: Build Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp libgtest*.a /usr/lib

      # Step 4: Configure and Build Project
      - name: Configure and Build Project
        run: |
          cmake -S . -B build
          cmake --build build

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
